<a href="https://colab.research.google.com/github/bluebluer/hello-wolrd/blob/master/hello-wolrd/python_pri/numpy_100exercise_%E4%B8%8A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
# 1.Import the numpy package under the name np
import numpy as np

# 2.Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

In [2]:
# 3.Create a null vector of size 10
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 4.How to find the memory size of any array
a=np.zeros((10,10))
print("%d bytes" %(a.size * a.itemsize))

800 bytes


In [6]:
# 5.How to get the doucumentation of the numpy add function from the command line?
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [7]:
# 6.Create a null vector of size 10 but the fifth value which is 1
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 7.Create a vector with values ranging from 10 to 49
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

列表[起始:终止:步长]，默认是my_list[0:-1:1]

my_list[1:2] # 等同于 my_list[1:2:1]<br>
my_list[:3]  # 等同于 my_list[0:3:1]<br>
my_list[::]  # 等同于 my_list[0:-1:1]<br>
my_list[1::3] # 等同于 my_list[1:-1:3]<br>


In [13]:
# 8.Reverse a vector(first element becomes last)
a=np.arange(20)
a=a[::-2]
a

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [14]:
# 9.Create a 3*3 matrix with values ranging from 0 to 8
a=np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
# 10.Find indices of non-zero elements from [1,2,0,0,4,0]
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

In [16]:
# 11.Create a 3*3 identity matrix
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# 12.Create a 3*3*3 array with random values
a=np.random.random((3,3,3))
a

array([[[0.98351121, 0.79507868, 0.99873382],
        [0.68380056, 0.10537898, 0.15257577],
        [0.14058123, 0.04188073, 0.20182911]],

       [[0.85548207, 0.5601843 , 0.75740906],
        [0.1064682 , 0.64538412, 0.3321438 ],
        [0.31669677, 0.48358696, 0.13588132]],

       [[0.99848068, 0.2006535 , 0.07220282],
        [0.03069173, 0.27351479, 0.20520831],
        [0.7585937 , 0.69001005, 0.74887901]]])

In [18]:
# 13.Create a 10*10 array with random values and find the minimum and maximum values
a=np.random.random((10,10))
min,max=a.min(),a.max()
min,max

(0.00893140039856255, 0.999966682702068)

In [24]:
# 14.Create a random vector of size 30 and find the mean value
a=np.random.random(30)
b=a.mean()
b

0.49211697380327846

In [25]:
# 15.Create a 2d array with 1 on the border and 0 inside
a=np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
# 16. How to add a border(filled with 0's) around an existing array?
a=np.ones((5,5))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [29]:
# Using fancy indexing
a=np.ones((5,5))
a[:,[0,-1]]=0
a[[0,-1],:]=0
a


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
# 17.What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [38]:
# 18.Create a 5*5 matrix with values 1,2,3,4 just below the diagonal
a=np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [41]:
# 19.Create a 8*8 matrix and fill it with a checkboard pattern
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
# 20.Consider a (6,7,8) shape array,what is the index(x,y,z) of the 100th element?
print(np.unravel_index(55,(6,7,8)))

(0, 6, 7)


In [47]:
import numpy as np
A = np.random.randint(1, 100, size = (2, 3, 5))
print(A)
ind_max=np.argmax(A)
print(ind_max)

[[[12 96 64 39 19]
  [54 58 77 31 60]
  [30 24 51 13 27]]

 [[58 16 55 16 57]
  [33 82 16 94 99]
  [44 15 62 74 60]]]
24


In [49]:
ind_max_src=np.unravel_index(ind_max,A.shape)
ind_max_src

(1, 1, 4)

In [51]:
# 21.Create a checkboard 8*8 matrix using the tile function
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [52]:
# 22.Normalize a 5*5 random matrix
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(a))
a

array([[-0.22920144,  1.21250124,  1.24689946,  0.6924551 , -1.03697284],
       [-0.18135867, -1.19249986,  0.84624456, -1.46458265,  0.46332374],
       [-1.60390156, -1.53925776,  1.30532925, -0.30566014,  0.76204713],
       [ 0.99154373,  0.61561428, -0.34910128, -0.39973299,  0.99245195],
       [-1.92351781,  0.90369085, -0.74714818,  0.90111402,  0.03971984]])

In [53]:
# 23.Create a custom dtype that describes a color as four unsigned byte(RGBA)
color=np.dtype([("r",np.ubyte),
        ("g",np.ubyte),
        ("b",np.ubyte),
        ("a",np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [56]:
# 24.Multiply a 5*3 matrix by 3*2(real matrix product)
z=np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [57]:
# 25.GIven a 1D array,negate all elements which are between 3 and 8,in place.
Z=np.arange(11)
Z[(3<Z) & (Z<8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [65]:
# 26.What is the output of the following script
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [67]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [69]:
# 27.Consider an integer vector Z,which of these expressions are legal
print(Z**Z)
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: ignored

In [70]:
# 28.What are the result of the following expressions
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]
nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  import sys


In [71]:
# 29 How to round away from zero a float array?
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-4.  3. -5. -2. -3.  2.  3.  4. -2. -3.]
[-4.  3. -5. -2. -3.  2.  3.  4. -2. -3.]


In [75]:
# 30.How to find common values between two arrays?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2,np.intersect1d(Z1,Z2))

[3 4 7 5 2 0 8 0 6 6] [7 4 4 0 1 9 2 5 6 8] [0 2 4 5 6 7 8]


In [76]:
# 31.How to ignore all numpy warnings(not recommended)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

In [77]:
# 32.Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [78]:
# 33.How to get the dates of yesterday,today and tomorrow？
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-07-03 2022-07-04 2022-07-05


In [79]:
# 34.How to get all the dates corresponding to the month of July 2016?
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [86]:
# 35.How to compute ((A+B)*(-A/2)) in place (without copy)?
A=np.ones(3)*1
B=np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


In [82]:
# 36.Extract the integer part of a random array of positive numbers using 4 different methods
X=np.random.uniform(0,10,10)
print(X-X%1)
print(X//1)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))

[0. 3. 7. 1. 2. 8. 9. 7. 8. 4.]
[0. 3. 7. 1. 2. 8. 9. 7. 8. 4.]
[0. 3. 7. 1. 2. 8. 9. 7. 8. 4.]
[0 3 7 1 2 8 9 7 8 4]
[0. 3. 7. 1. 2. 8. 9. 7. 8. 4.]


In [85]:
# 37.Create a 5*5 matrix with row values ranging from 0 to 4
Z =np.zeros((5,5))
Z +=np.arange(5)
print(Z)

#without broadcasting
Z=np.tile(np.arange(0,5),(5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [87]:
# 38.Consider a generator function that generates 10 integers and use it to build an array
def generate():
  for x in range(10):
    yield x
Z =np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [88]:
# 39.Create a vector of size 10 with values ranging from 0 to 1,both excluded
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [89]:
# 40.Create a random vector of size 10 and sort it
Z=np.random.random(10)
Z.sort()
print(Z)

[0.06131553 0.18558007 0.37066395 0.45613905 0.61408071 0.61475042
 0.81358414 0.82544356 0.92945893 0.99137234]


In [90]:
# 41. How to sum a small array fster than np.sum?
Z=np.arange(10)
np.add.reduce(Z)

45

In [115]:
# 42.Consider two random array A and B,check if they are equal
A=np.random.randint(0,2,2)
B=np.random.randint(0,2,2)
print(A,B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal=np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

[1 1] [1 0]
False
False


In [117]:
# 43.Make an array immutable(read-only)
Z=np.zeros(10)
Z.flags.writeable=False
Z[0]=1


ValueError: ignored

In [118]:
# 44.Consider a random 10*2 matrix representing cartesian coordinates,convert them to polar coordinates
Z =np.random.random((10,2))
X,Y=Z[:,0],Z[:,1]
R=np.sqrt(X**2+Y**2)
T=np.arctan2(Y,X)
print(R)
print(T)

[1.27702563 1.24694611 0.88420394 0.97362258 0.95219669 0.64417312
 0.60278326 1.16033356 0.87690777 1.16184838]
[0.72008911 0.72330323 1.27821949 1.49219621 1.52358744 0.18630178
 0.71673107 0.5651856  1.32676839 0.57306731]


In [119]:
# 45.Create random vector of size 10 and replace the maximum value by 0
Z=np.random.random(10)
Z[Z.argmax()] =0
print(Z)

[0.68463393 0.16282714 0.16052152 0.91505163 0.         0.34104479
 0.67071337 0.54880416 0.68123009 0.49052053]


In [120]:
# 46 Create a structured array with 'x' and 'y' coordinates covering the [0,1]*[0,1] area
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] =np.meshgrid(np.linspace(0,1,5),
              np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [121]:
Z['x']

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [125]:
# 47.Given two array,X and Y,construct the Cauchy matrix C (Cij =1/(xi - yj))
X=np.arange(8)
Y=X+0.5
C =1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.163637117973


In [126]:
# 48 Print the minimum and maximum representable value for each numpy sclar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [127]:
# 49.How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [130]:
# 50.How to find closest value(to given scalar)in a vector?
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

51
