<a href="https://colab.research.google.com/github/bluebluer/hello-wolrd/blob/master/dongshouDL05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y ,x-y

(tensor([5.]), tensor([1.]))

In [3]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [4]:
# A的转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [5]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
# 通过分配新的内存，将一个副本分给B
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [6]:
# 两个元素按元素乘法称为哈达玛积
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [7]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a+X,(a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [8]:
a * X 

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [12]:
# 计算其元素的和
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [18]:
# 表示任意形状张量的元素和
A = torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [14]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]), torch.Size([5, 4]))

In [15]:
# 两个维度求和
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [20]:
# 与求和相关的量是平均值
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [21]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]), tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [22]:
# 计算和或均值时保持轴数不变
sum_A = A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [23]:
# 通过广播将A/sum_A
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [25]:
# 某个轴计算A元素
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [30]:
# 矩阵向量积
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [31]:
torch.mv(A,x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [33]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [35]:
# 2范数
# xi 向量元素平方和开根号
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [36]:
# L1 范数，向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [37]:
# F 范数是矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

In [38]:
a = torch.ones((2,5,4))
a.shape

torch.Size([2, 5, 4])

In [39]:
a.sum(axis=(0,2)).shape

torch.Size([5])

In [40]:
a.sum(axis=1,keepdims=True).shape

torch.Size([2, 1, 4])