<a href="https://colab.research.google.com/github/bluebluer/hello-wolrd/blob/master/python_pri%5Cnumpy_100exercise_%E4%B8%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 51.Create a structured array represeting a position (x,y) and a color(r,g,b)
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  import sys


In [14]:
# 52.Consider a random vector with shape (100,2) representing coordinates
# find point by point distances
Z =np.random.random((10,2))
X,Y=np.atleast_2d(Z[:,0],Z[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(X,X.shape)
print(X.T,X.T.shape)

#print(Y)


[[0.3567001  0.31840606 0.96182761 0.1593021  0.60163578 0.1140036
  0.87893502 0.27278603 0.59083486 0.17608495]] (1, 10)
[[0.3567001 ]
 [0.31840606]
 [0.96182761]
 [0.1593021 ]
 [0.60163578]
 [0.1140036 ]
 [0.87893502]
 [0.27278603]
 [0.59083486]
 [0.17608495]] (10, 1)


In [15]:
# Much fster with scipy
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.7353081  0.63911939 0.03887738 0.34483151 0.26872696
  0.59291331 0.1358569  0.62700006 0.44601974]
 [0.7353081  0.         0.79118784 0.69720766 0.67256122 0.80819144
  0.99088936 0.6230815  0.29134632 0.8966966 ]
 [0.63911939 0.79118784 0.         0.63424005 0.29611659 0.90199783
  0.28089793 0.5398067  0.50410224 0.30643376]
 [0.03887738 0.69720766 0.63424005 0.         0.33824543 0.26793454
  0.60546644 0.11028763 0.59522444 0.45877355]
 [0.34483151 0.67256122 0.29611659 0.33824543 0.         0.60589568
  0.34118699 0.24559839 0.44190604 0.22541363]
 [0.26872696 0.80819144 0.90199783 0.26793454 0.60589568 0.
  0.85775622 0.36696075 0.79235292 0.7113785 ]
 [0.59291331 0.99088936 0.28089793 0.60546644 0.34118699 0.85775622
  0.         0.54878774 0.72550115 0.1469123 ]
 [0.1358569  0.6230815  0.5398067  0.11028763 0.24559839 0.36696075
  0.54878774 0.         0.49292131 0.40633731]
 [0.62700006 0.29134632 0.50410224 0.59522444 0.44190604 0.79235292
  0.72550115 0.49292

In [18]:
# 53.How to convert a float array into an inerger in place?
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[79 14 62 69 12 32  5 85 35 92]


In [19]:
# 54.How to read the following file?
# 1,2,3,4,5.....
from io import StringIO
s=StringIO("""1,2,3,4,5
      6, , ,7,8
      , ,9,10,11
""")
Z=np.genfromtxt(s,delimiter=',',dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [20]:
# 55.What is the equivalent of enumerate for numpy arrays?
Z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
  print(index,value)
for index in np.ndindex(Z.shape):
  print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [24]:
# 56.Generate a generic 2D Gauussian-like array
X,Y =np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma,mu=1.0,0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [25]:
# 57.How to randomly place p elements in a 2D array?
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [28]:
# 58.Subtract the mean of each row of a matrix
X=np.random.rand(5,10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)

[[ 0.11159631  0.30809289  0.35251782  0.14713097 -0.39610839  0.17973591
  -0.21018382 -0.15513876  0.01748516 -0.35512808]
 [ 0.18862931 -0.02125829  0.11154367 -0.05393577 -0.26101982  0.23568992
   0.20150993 -0.337819   -0.00825063 -0.05508932]
 [-0.128826    0.25156607 -0.51470947  0.0677926  -0.26723013 -0.30471889
   0.22848321  0.18777403  0.44459133  0.03527725]
 [ 0.26210651 -0.42738919 -0.34936707 -0.06356259  0.18679066  0.12916791
   0.02554548  0.37807159 -0.11098865 -0.03037466]
 [ 0.4306491   0.03014692 -0.10060849  0.00235109 -0.11855226  0.48033078
  -0.15108087 -0.48808232 -0.49550973  0.41035577]]


In [33]:
# 59 How to sort an array by the nth column?
Z=np.random.randint(0,10,(4,4))
print(Z)
print(Z[Z[:,1].argsort()])
Z[:,1].argsort()

[[0 4 5 3]
 [0 0 5 5]
 [1 8 5 6]
 [6 5 3 7]]
[[0 0 5 5]
 [0 4 5 3]
 [6 5 3 7]
 [1 8 5 6]]


array([1, 0, 3, 2])

In [54]:
# 60.How to tell if a given 2D array has null columns?
Z=np.random.randint(0,4,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[3 0 1 3 0 1 3 2 0 2]
 [2 0 3 2 0 1 2 3 1 0]
 [0 0 2 0 1 0 3 3 3 2]]
True


In [58]:
# 61.Find the nearest value from a given value in an array
Z=np.random.uniform(0,1,10)
z=0.5
m=Z.flat[np.abs(Z-z).argmin()]
print(m)

0.5180687317121399


In [59]:
# 62.Considering two arrays with shape (1,3) and (3,1)
# how to compute their sum using an iterator?
A =np.arange(3).reshape(3,1)
B =np.arange(3).reshape(1,3)
it =np.nditer([A,B,None])
for x,y,z in it:z[...] =x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [60]:
# 63.Create an array class that has name attibute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


In [63]:
# 64.Consider a given vector,how to add 1 to each element indexed by a second vector
# (be careful with repeated indices)? 
Z=np.ones(10)
print(Z)
I=np.random.randint(0,len(Z),20)
print(I)
Z +=np.bincount(I,minlength=len(Z))
print(Z)

#Anther solution
np.add.at(Z,I,1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 9 0 6 8 4 5 8 9 3 7 5 8 0 4 4 3 5 7 3]
[3. 1. 2. 4. 4. 4. 2. 3. 4. 3.]
[5. 1. 3. 7. 7. 7. 3. 5. 7. 5.]


In [65]:
# 65.How to accumulate elements of vector X to an array F based on an idnex list I
X =[1,2,3,4,5,6]
I =[1,3,9,3,4,1]
F =np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [67]:
# 66.Considering a(w,h,3) image of (dtype=ubyte),compute number of unique colors
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


In [68]:
# 67.Considering a four dimensions array,how to get sum over the last two axis at once?
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[41 52 57 44]
 [53 44 44 58]
 [38 52 46 46]]
[[41 52 57 44]
 [53 44 44 58]
 [38 52 46 46]]


In [69]:
# 68.Considering a one-dimensional vector D, how to compute means of subsets of D using a 
# vector S of same size describing subset  indices? 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.56688354 0.47840131 0.55465416 0.53999816 0.38172057 0.59913929
 0.52152045 0.52111003 0.52124984 0.51435806]


In [70]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.566884
1    0.478401
2    0.554654
3    0.539998
4    0.381721
5    0.599139
6    0.521520
7    0.521110
8    0.521250
9    0.514358
dtype: float64


In [71]:
# 69 How to get the diagonal of a dot product?
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.6631544 , 0.99740018, 2.04681567, 1.58572868, 1.03538006])

In [72]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector
# with 3 consecutive zeros interleaved between each value? 
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [73]:
# 71.Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [74]:
# 72. How to swap two rows of an array? 
A =np.arange(25).reshape(5,5)
A[[0,1]] =A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [75]:
# 73. Consider a set of 10 triplets describing 10 triangles 
#(with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 63) ( 1, 79) ( 2, 59) ( 2, 98) ( 4, 56) ( 4, 99) ( 5, 18) ( 5, 84)
 ( 7, 73) ( 7, 82) (10, 64) (10, 88) (18, 27) (18, 84) (18, 97) (26, 38)
 (26, 52) (27, 97) (34, 74) (34, 98) (38, 52) (40, 91) (40, 94) (56, 99)
 (59, 98) (63, 79) (64, 88) (73, 82) (74, 98) (91, 94)]


In [76]:
# 74. Given a sorted array C that corresponds to a bincount, 
# how to produce an array A such that np.bincount(A) == C?
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [77]:
# 75. How to compute averages using a sliding window over an array?
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
