<a href="https://colab.research.google.com/github/bluebluer/hello-wolrd/blob/master/pytorch_pri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
?torch.tensor
"""
  tensor(data, *, dtype=None, 
  device=None, requires_grad=False, pin_memory=False) -> Tensor
"""

In [3]:
# 创建tensor，用dtype指定类型
a = torch.tensor(1.0,dtype=torch.float)
b = torch.tensor(1,dtype=torch.long)
c = torch.tensor(1.0,dtype=torch.int8)
print(a,b,c)

tensor(1.) tensor(1) tensor(1, dtype=torch.int8)


In [14]:
# 使用指定类型函数随机初始化指定大小的tensor
d = torch.FloatTensor(2,3)
e = torch.IntTensor(2)
f = torch.IntTensor([1,2,3,4])
print(d,'\n',e,'\n',f)

tensor([[2.3308e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.5554e-43]]) 
 tensor([100129088,         0], dtype=torch.int32) 
 tensor([1, 2, 3, 4], dtype=torch.int32)


In [15]:
# tensor和numpy array之间的相互转换
import numpy as np
g = np.array([[1,2,3],[4,5,6]])
h = torch.tensor(g)
print(g,'\n',h)

[[1 2 3]
 [4 5 6]] 
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
i = torch.from_numpy(g)
print(i)
j = h.numpy()
print(j)

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


In [17]:
# 常见的构造Tnesor的函数
k = torch.rand(2,3)
l = torch.ones(2,3)
m = torch.zeros(2,3)
n = torch.arange(0,10,2)
print(k,'\n',l,'\n',m,'\n',n)

tensor([[0.1942, 0.1981, 0.0044],
        [0.6289, 0.1263, 0.9129]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([0, 2, 4, 6, 8])


In [18]:
# 查看tensor的维度信息
print(k.shape)
print(k.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [19]:
# torch的运算
print(torch.add(k,1))

tensor([[1.1942, 1.1981, 1.0044],
        [1.6289, 1.1263, 1.9129]])


In [20]:
# tensor的索引方式与numpy相似
o = torch.add(k,1)
print(o[:,1])
print(o[0,:])


tensor([1.1981, 1.1263])
tensor([1.1942, 1.1981, 1.0044])


In [21]:
# 改变tensor的形状 view
print(o.view(3,2))
print(o.view(-1,2))

tensor([[1.1942, 1.1981],
        [1.0044, 1.6289],
        [1.1263, 1.9129]])
tensor([[1.1942, 1.1981],
        [1.0044, 1.6289],
        [1.1263, 1.9129]])


In [22]:
# tensor的广播机制
p = torch.arange(1,3).view(1,2)
print(p)
q = torch.arange(1,4).view(3,1)
print(q)
print(p+q)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [23]:
# 扩展压缩tensor维度:squeeze
print(o)
r = o.unsqueeze(1)
print(r)
print(r.shape)

tensor([[1.1942, 1.1981, 1.0044],
        [1.6289, 1.1263, 1.9129]])
tensor([[[1.1942, 1.1981, 1.0044]],

        [[1.6289, 1.1263, 1.9129]]])
torch.Size([2, 1, 3])


In [24]:
# 只有维度为一的时候才可以压缩squueze
s = r.squeeze(0)
print(s)
print(s.shape)

tensor([[[1.1942, 1.1981, 1.0044]],

        [[1.6289, 1.1263, 1.9129]]])
torch.Size([2, 1, 3])


In [25]:
t = r.squeeze(1)
print(t)
print(t.shape)

tensor([[1.1942, 1.1981, 1.0044],
        [1.6289, 1.1263, 1.9129]])
torch.Size([2, 3])
